name: Build development and deploy it

on:
  push:
    branches:
      - main

env:
  URL: test.intia.de

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://${{ env.URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Using cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Push cname to page
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          echo ${{ env.URL }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git push

      - name: Build Site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_TOKEN }}
          target_branch: "gh-pages"
