name: Build production and deploy it

on:
  push:
    branches:
      - production

env:
  URL: intia.de

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Using cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-v2-

      - name: Build Site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_TOKEN }}
          target_path: "build"

      - name: Checkout Prod Target
        uses: actions/checkout@v2.4.0
        with:
          repository: th-koeln-intia/intia-prod
          path: "deploy"
          token: ${{ secrets.PAT }}

      - name: Push files to target
        run: |
          rm -r deploy/*
          cp -r build/* deploy
          cd deploy
          echo ${{ env.URL }} > CNAME
          rm -r ./admin
          git add .
          git commit -m $GITHUB_SHA
          git push
