name: Update production

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"

env:
  URL: intia.de

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Push to production
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git Checkout production
          git commit -m $GITHUB_SHA
          git push
