name: Update production

on:
  push:
    branches:
      - main

env:
  URL: intia.de

jobs:
  build-test:
    runs-on: ubuntu-20.04
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          ref: "main"

      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          ref: "production"
          path: "destination"
          token: ${{ secrets.PAT }}

      - name: Push to production
        run: |
          rsync -Rr . destination
          cd destination
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git status
          git echo "-------------------------"
          git add .
          git echo "-------------------------"
          git status
          git commit -m $GITHUB_SHA
          git status
          git push
