name: Update production

on:
  push:
    branches:
      - main

env:
  URL: intia.de

jobs:
  build-test:
    runs-on: ubuntu-20.04
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          ref: "main"

      - name: Checkout repo
        uses: actions/checkout@v2.4.0
        with:
          ref: "production"
          path: "destination"
          token: ${{ secrets.PAT }}

      - name: Push to production
        run: |
          cd destination
          rm -rf *
          cp -r ../ .
          echo " 1 -------------------------"
          ls -a
          find . -name .git -type d -prune
          echo " 3 -------------------------"
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git status
          echo " 4 -------------------------"
          git add .
          echo " 5 -------------------------"
          git status
          git commit -m $GITHUB_SHA
          git status
          git push
